In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [354]:
datos_disney = pd.read_csv('disney_plus_titles-score.csv')

In [355]:
datos_disney.isna().sum()

show_id           0
type              0
title             0
director        473
cast            190
country         219
date_added        3
release_year      0
rating            3
duration          0
listed_in         0
description       0
score             0
dtype: int64

In [356]:
datos_disney.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!,100
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...,17
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.,92
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!",35
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...,11

                                                        TRANSFORMACIONES

                                    Transformaciones para el dataframe datos_disney

Generar campo id: Cada id se compondrá de la primera letra del nombre de la plataforma, seguido del show_id ya presente en los datasets (ejemplo para títulos de Amazon = as123)

In [357]:
## Esta función concatenara la inicial de disney a la columna show_id
def funcion(var):
    return 'd' + var

In [358]:
## Probando para ver si la funcion logra su cometido
lista = ['ca','ce', 'ci', 'co','cu']
for item in lista:
    print(funcion(item))

dca
dce
dci
dco
dcu

In [359]:
lista = datos_disney.loc[:,'show_id'] ## Copiar la columna show_id para poder modificarla esto con el fin de evitar errores en los datos
##Esto nos devolvera una serie y la transformamos a lista con el metodo list()
lista = list(lista)

In [360]:
##creamos una lista vacia para agregar los valores que modifiquemos
lista_transformada = [] ##Ya tenemos la lista ahora aplicamos la función
for item in lista:
    lista_transformada = lista_transformada + [funcion(item)]

In [361]:
##Eliminamos la columna show_id
del datos_disney['show_id']

In [362]:
## Acá agregaré la lista ya transformada 
datos_disney['Id'] = pd.Series(lista_transformada)

In [363]:
#visualizamos
datos_disney

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,Id
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!,100,ds1
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...,17,ds2
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.,92,ds3
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!",35,ds4
4,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...,11,ds5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445,Movie,X-Men Origins: Wolverine,Gavin Hood,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...","United States, United Kingdom","June 4, 2021",2009,PG-13,108 min,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...,53,ds1446
1446,Movie,Night at the Museum: Battle of the Smithsonian,Shawn Levy,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...","United States, Canada","April 2, 2021",2009,PG,106 min,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...,75,ds1447
1447,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States","December 18, 2020",2016,PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum...",89,ds1448
1448,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States","September 18, 2020",2003,PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...,77,ds1449
1449,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,"April 1, 2020",2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.,88,ds1450

Los valores nulos del campo rating deberán reemplazarse por el string “G” (corresponde al maturity rating: “general for all audiences”

In [364]:
##Para reemplazar los valores null en la columna rating (reemplazamos por la letra G)
datos_disney['rating'].fillna('G', inplace=True)

In [365]:
##Comprobamos para ver si existen valores nulos en la columna rating
datos_disney['rating'].isna().sum()

0

De haber fechas, deberán tener el formato AAAA-mm-dd

In [366]:
## se extraera la columna date_added al formato AAAA-MM-DD

fechas = pd.to_datetime(datos_disney['date_added'])
fechas = list(fechas)
del datos_disney['date_added']
datos_disney['date_added'] = pd.Series(fechas)

In [367]:
datos_disney.head(12)

,type,title,director,cast,country,release_year,rating,duration,listed_in,description,score,Id,date_added
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!,100,ds1,2021-11-26
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...,17,ds2,2021-11-26
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.,92,ds3,2021-11-26
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!",35,ds4,2021-11-26
4,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,2021,G,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...,11,ds5,2021-11-25
5,Movie,Becoming Cousteau,Liz Garbus,"Jacques Yves Cousteau, Vincent Cassel",United States,2021,PG-13,94 min,"Biographical, Documentary",An inside look at the legendary life of advent...,18,ds6,2021-11-24
6,TV Show,Hawkeye,NaN,"Jeremy Renner, Hailee Steinfeld, Vera Farmiga,...",NaN,2021,TV-14,1 Season,"Action-Adventure, Superhero",Clint Barton/Hawkeye must team up with skilled...,98,ds7,2021-11-24
7,TV Show,Port Protection Alaska,NaN,"Gary Muehlberger, Mary Miller, Curly Leach, Sa...",United States,2015,TV-14,2 Seasons,"Docuseries, Reality, Survival",Residents of Port Protection must combat volat...,60,ds8,2021-11-24
8,TV Show,Secrets of the Zoo: Tampa,NaN,"Dr. Ray Ball, Dr. Lauren Smith, Chris Massaro,...",United States,2019,TV-PG,2 Seasons,"Animals & Nature, Docuseries, Family",A day in the life at ZooTampa is anything but ...,53,ds9,2021-11-24
9,Movie,A Muppets Christmas: Letters To Santa,Kirk R. Thatcher,"Steve Whitmire, Dave Goelz, Bill Barretta, Eri...",United States,2008,G,45 min,"Comedy, Family, Musical",Celebrate the holiday season with all your fav...,7,ds10,2021-11-19
10,Movie,Adventure Thru the Walt Disney Archives,John Gleim,"Don Hahn, Kathryn Beaumont, Pete Docter, Kevin...",NaN,2020,TV-PG,59 min,Documentary,Explore the treasures and rich history of the ...,17,ds11,2021-11-19
11,Movie,Puppy for Hanukkah,NaN,NaN,NaN,2020,TV-G,4 min,"Comedy, Family, Music","Check out Daveed Digg's official music video ""...",85,ds12,2021-11-19

Los campos de texto deberán estar en minúsculas, sin excepciones

In [368]:
##se usara el metodo lower para cambiar todos los textos a minusculas
datos_disney['type'] = datos_disney['type'].str.lower()
datos_disney['title'] = datos_disney['title'].str.lower()
datos_disney['director'] = datos_disney['director'].str.lower()
datos_disney['cast'] = datos_disney['cast'].str.lower()
datos_disney['country'] = datos_disney['country'].str.lower()
datos_disney['listed_in'] = datos_disney['listed_in'].str.lower()
datos_disney['description'] = datos_disney['description'].str.lower()

El campo duration debe convertirse en dos campos: duration_int y duration_type. El primero será un integer y el segundo un string indicando la unidad de medición de duración: min (minutos) o season (temporadas)

In [369]:
##Uso el metodo split para dividir la columna duration 
datos_disney[['duration_int','duration_type']] = datos_disney['duration'].str.split(expand=True)

In [370]:
##chusmeamos :P
datos_disney.head(10)

,type,title,director,cast,country,release_year,rating,duration,listed_in,description,score,Id,date_added,duration_int,duration_type
0,movie,duck the halls: a mickey mouse christmas special,"alonso ramirez ramos, dave wasson","chris diamantopoulos, tony anselmo, tress macn...",NaN,2016,TV-G,23 min,"animation, family",join mickey and the gang as they duck the halls!,100,ds1,2021-11-26,23,min
1,movie,ernest saves christmas,john cherry,"jim varney, noelle parker, douglas seale",NaN,1988,PG,91 min,comedy,santa claus passes his magic bag to a new st. ...,17,ds2,2021-11-26,91,min
2,movie,ice age: a mammoth christmas,karen disher,"raymond albert romano, john leguizamo, denis l...",united states,2011,TV-G,23 min,"animation, comedy, family",sid the sloth is on santa's naughty list.,92,ds3,2021-11-26,23,min
3,movie,the queen family singalong,hamish hamilton,"darren criss, adam lambert, derek hough, alexa...",NaN,2021,TV-PG,41 min,musical,"this is real life, not just fantasy!",35,ds4,2021-11-26,41,min
4,tv show,the beatles: get back,NaN,"john lennon, paul mccartney, george harrison, ...",NaN,2021,G,1 Season,"docuseries, historical, music",a three-part documentary from peter jackson ca...,11,ds5,2021-11-25,1,Season
5,movie,becoming cousteau,liz garbus,"jacques yves cousteau, vincent cassel",united states,2021,PG-13,94 min,"biographical, documentary",an inside look at the legendary life of advent...,18,ds6,2021-11-24,94,min
6,tv show,hawkeye,NaN,"jeremy renner, hailee steinfeld, vera farmiga,...",NaN,2021,TV-14,1 Season,"action-adventure, superhero",clint barton/hawkeye must team up with skilled...,98,ds7,2021-11-24,1,Season
7,tv show,port protection alaska,NaN,"gary muehlberger, mary miller, curly leach, sa...",united states,2015,TV-14,2 Seasons,"docuseries, reality, survival",residents of port protection must combat volat...,60,ds8,2021-11-24,2,Seasons
8,tv show,secrets of the zoo: tampa,NaN,"dr. ray ball, dr. lauren smith, chris massaro,...",united states,2019,TV-PG,2 Seasons,"animals & nature, docuseries, family",a day in the life at zootampa is anything but ...,53,ds9,2021-11-24,2,Seasons
9,movie,a muppets christmas: letters to santa,kirk r. thatcher,"steve whitmire, dave goelz, bill barretta, eri...",united states,2008,G,45 min,"comedy, family, musical",celebrate the holiday season with all your fav...,7,ds10,2021-11-19,45,min

Ahora se hacen las mismas modificaciones a los otros 3 dataframes

                                        Transformaciones para el dataframe datos_amazon

Generar campo id: Cada id se compondrá de la primera letra del nombre de la plataforma, seguido del show_id ya presente en los datasets (ejemplo para títulos de Amazon = as123)

In [371]:
data_amazon = pd.read_csv('amazon_prime_titles-score.csv')

In [376]:
data_amazon.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,Id
0,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...,99,as1
1,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,37,as2
2,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,20,as3
3,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",27,as4
4,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,75,as5

In [373]:
## Esta función concatenara la inicial de amazon a la columna show_id
def funcion(var):
    return 'a' + var

In [374]:
lista = data_amazon.loc[:,'show_id'] ## Copiar la columna show_id para poder modificarla esto con el fin de evitar errores en los datos
##Esto nos devolvera una serie y la transformamos a lista con el metodo list()
lista = list(lista)

lista_transformada = [] ##creamos una lista vacia donde se iran agregando los id modificados
for item in lista:
    lista_transformada = lista_transformada + [funcion(item)]

In [375]:
del data_amazon['show_id'] ##borro la columna show_id ya no es necesaria

## Acá agregaré la lista ya transformada 
data_amazon['Id'] = pd.Series(lista_transformada)

In [382]:
data_amazon.head(5)

,type,title,director,cast,country,release_year,rating,duration,listed_in,description,score,Id,date_added
0,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2014,G,113 min,"Comedy, Drama",A small fishing village must procure a local d...,99,as1,2021-03-30
1,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,37,as2,2021-03-30
2,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2017,G,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,20,as3,2021-03-30
3,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2014,G,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",27,as4,2021-03-30
4,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,1989,G,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,75,as5,2021-03-30

De haber fechas, deberán tener el formato AAAA-mm-dd

In [379]:
## se extraera la columna date_added al formato AAAA-MM-DD

fechas = pd.to_datetime(data_amazon['date_added'])
fechas = list(fechas)
del data_amazon['date_added']
data_amazon['date_added'] = pd.Series(fechas)

Los valores nulos del campo rating deberán reemplazarse por el string “G” (corresponde al maturity rating: “general for all audiences”

In [381]:
##Para reemplazar los valores null en la columna rating (reemplazamos por la letra G)
data_amazon['rating'].fillna('G', inplace=True)

Los campos de texto deberán estar en minúsculas, sin excepciones

In [383]:
##se usara el metodo lower para cambiar todos los textos a minusculas
data_amazon['type'] = data_amazon['type'].str.lower()
data_amazon['title'] = data_amazon['title'].str.lower()
data_amazon['director'] = data_amazon['director'].str.lower()
data_amazon['cast'] = data_amazon['cast'].str.lower()
data_amazon['country'] = data_amazon['country'].str.lower()
data_amazon['listed_in'] = data_amazon['listed_in'].str.lower()
data_amazon['description'] = data_amazon['description'].str.lower()

El campo duration debe convertirse en dos campos: duration_int y duration_type. El primero será un integer y el segundo un string indicando la unidad de medición de duración: min (minutos) o season (temporadas)

In [384]:
##Uso el metodo split para dividir la columna duration 
data_amazon[['duration_int','duration_type']] = data_amazon['duration'].str.split(expand=True)

In [385]:
data_amazon.head(10)

,type,title,director,cast,country,release_year,rating,duration,listed_in,description,score,Id,date_added,duration_int,duration_type
0,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2014,G,113 min,"comedy, drama",a small fishing village must procure a local d...,99,as1,2021-03-30,113,min
1,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,37,as2,2021-03-30,110,min
2,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2017,G,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,20,as3,2021-03-30,74,min
3,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2014,G,69 min,documentary,"pink breaks the mold once again, bringing her ...",27,as4,2021-03-30,69,min
4,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,1989,G,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,75,as5,2021-03-30,45,min
5,movie,living with dinosaurs,paul weiland,"gregory chisholm, juliet stevenson, brian hens...",united kingdom,1989,G,52 min,"fantasy, kids",the story unfolds in a an english seaside town...,74,as6,2021-03-30,52,min
6,movie,hired gun,fran strine,"alice cooper, liberty devitto, ray parker jr.,...",united states,2017,G,98 min,"documentary, special interest","they are the ""first call, a-list"" musicians, j...",50,as7,2021-03-30,98,min
7,movie,grease live!,"thomas kail, alex rudzinski","julianne hough, aaron tveit, vanessa hudgens, ...",united states,2016,G,131 min,comedy,"this honest, uncompromising comedy chronicles ...",84,as8,2021-03-30,131,min
8,movie,global meltdown,daniel gilboy,"michael paré, leanne khol young, patrick j. ma...",canada,2017,G,87 min,"action, science fiction, suspense",a helicopter pilot and an environmental scient...,46,as9,2021-03-30,87,min
9,movie,david's mother,robert allan ackerman,"kirstie alley, sam waterston, stockard channing",united states,1994,G,92 min,drama,sally goodson is a devoted mother to her autis...,70,as10,2021-04-01,92,min

                                        Transformaciones para el dataframe datos_hulu

In [387]:
data_hulu = pd.read_csv('hulu_titles-score (2).csv')

In [388]:
data_hulu.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...,48
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r...",8
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...,8
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...,33
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...,24

Generar campo id: Cada id se compondrá de la primera letra del nombre de la plataforma, seguido del show_id ya presente en los datasets (ejemplo para títulos de Amazon = as123)

In [389]:
## Esta función concatenara la inicial de hulu a la columna show_id
def funcion(var):
    return 'h' + var

In [390]:
lista = data_hulu.loc[:,'show_id'] ## Copiar la columna show_id para poder modificarla esto con el fin de evitar errores en los datos
##Esto nos devolvera una serie y la transformamos a lista con el metodo list()
lista = list(lista)

lista_transformada = [] ##creamos una lista vacia donde se iran agregando los id modificados
for item in lista:
    lista_transformada = lista_transformada + [funcion(item)]

In [391]:
del data_hulu['show_id'] ##borro la columna show_id ya no es necesaria

## Acá agregaré la lista ya transformada 
data_hulu['Id'] = pd.Series(lista_transformada)

In [392]:
data_hulu.head(3)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,Id
0,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...,48,hs1
1,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r...",8,hs2
2,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...,8,hs3

De haber fechas, deberán tener el formato AAAA-mm-dd

In [393]:
## se extraera la columna date_added al formato AAAA-MM-DD

fechas = pd.to_datetime(data_hulu['date_added'])
fechas = list(fechas)
del data_hulu['date_added']
data_hulu['date_added'] = pd.Series(fechas)

Los valores nulos del campo rating deberán reemplazarse por el string “G” (corresponde al maturity rating: “general for all audiences”

In [395]:
##Para reemplazar los valores null en la columna rating (reemplazamos por la letra G)
data_hulu['rating'].fillna('G', inplace=True)

Los campos de texto deberán estar en minúsculas, sin excepciones

In [398]:
##se usara el metodo lower para cambiar todos los textos a minusculas
data_hulu['type'] = data_hulu['type'].str.lower()
data_hulu['title'] = data_hulu['title'].str.lower()
data_hulu['director'] = data_hulu['director'].str.lower()

data_hulu['country'] = data_hulu['country'].str.lower()
data_hulu['listed_in'] = data_hulu['listed_in'].str.lower()
data_hulu['description'] = data_hulu['description'].str.lower()

In [407]:
data_hulu['cast'] = data_hulu['cast'].astype(str).str.lower()

El campo duration debe convertirse en dos campos: duration_int y duration_type. El primero será un integer y el segundo un string indicando la unidad de medición de duración: min (minutos) o season (temporadas)

In [408]:
##Uso el metodo split para dividir la columna duration 
data_hulu[['duration_int','duration_type']] = data_hulu['duration'].str.split(expand=True)

In [409]:
data_hulu.head(8)

,type,title,director,cast,country,release_year,rating,duration,listed_in,description,score,Id,date_added,duration_int,duration_type
0,movie,ricky velez: here's everything,NaN,nan,NaN,2021,TV-MA,NaN,"comedy, stand up",​comedian ricky velez bares it all with his ho...,48,hs1,2021-10-24,NaN,NaN
1,movie,silent night,NaN,nan,NaN,2020,G,94 min,"crime, drama, thriller","mark, a low end south london hitman recently r...",8,hs2,2021-10-23,94,min
2,movie,the marksman,NaN,nan,NaN,2021,PG-13,108 min,"action, thriller",a hardened arizona rancher tries to protect an...,8,hs3,2021-10-23,108,min
3,movie,gaia,NaN,nan,NaN,2021,R,97 min,horror,a forest ranger and two survivalists with a cu...,33,hs4,2021-10-22,97,min
4,movie,settlers,NaN,nan,NaN,2021,G,104 min,"science fiction, thriller",mankind's earliest settlers on the martian fro...,24,hs5,2021-10-22,104,min
5,tv show,the halloween candy magic pet,NaN,nan,NaN,2021,G,1 Season,"family, kids",join mila and morphle on a mystery-filled hall...,45,hs6,2021-10-22,1,Season
6,movie,the evil next door,NaN,nan,NaN,2020,G,88 min,"horror, thriller","new to her role as a stepmom, a young woman mo...",37,hs7,2021-10-21,88,min
7,tv show,the next thing you eat,NaN,nan,NaN,2021,G,1 Season,"cooking & food, documentaries, lifestyle & cul...",with the unique insights and experience of ugl...,76,hs8,2021-10-21,1,Season

                                        Transformaciones para el dataframe datos_nexflix

In [410]:
data_nexflix = pd.read_csv('netflix_titles-score.csv')

In [411]:
data_nexflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",29
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",86
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,75
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",49
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,92

Generar campo id: Cada id se compondrá de la primera letra del nombre de la plataforma, seguido del show_id ya presente en los datasets (ejemplo para títulos de Amazon = as123)

In [412]:
## Esta función concatenara la inicial de nexflix a la columna show_id
def funcion(var):
    return 'n' + var

In [414]:
lista = data_nexflix.loc[:,'show_id'] ## Copiar la columna show_id para poder modificarla esto con el fin de evitar errores en los datos
##Esto nos devolvera una serie y la transformamos a lista con el metodo list()
lista = list(lista)

lista_transformada = [] ##creamos una lista vacia donde se iran agregando los id modificados
for item in lista:
    lista_transformada = lista_transformada + [funcion(item)]

del data_nexflix['show_id'] ##borro la columna show_id ya no es necesaria

## Acá agregaré la lista ya transformada 
data_nexflix['Id'] = pd.Series(lista_transformada)

Los valores nulos del campo rating deberán reemplazarse por el string “G” (corresponde al maturity rating: “general for all audiences”

In [417]:
##Para reemplazar los valores null en la columna rating (reemplazamos por la letra G)
data_nexflix['rating'].fillna('G', inplace=True)

De haber fechas, deberán tener el formato AAAA-mm-dd

In [418]:
## se extraera la columna date_added al formato AAAA-MM-DD

fechas = pd.to_datetime(data_nexflix['date_added'])
fechas = list(fechas)
del data_nexflix['date_added']
data_nexflix['date_added'] = pd.Series(fechas)

In [423]:
data_nexflix

,type,title,director,cast,country,release_year,rating,duration,listed_in,description,score,Id,date_added,duration_int,duration_type
0,movie,dick johnson is dead,kirsten johnson,NaN,united states,2020,PG-13,90 min,documentaries,"as her father nears the end of his life, filmm...",29,ns1,2021-09-25,90,min
1,tv show,blood & water,NaN,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,2021,TV-MA,2 Seasons,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",86,ns2,2021-09-24,2,Seasons
2,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",NaN,2021,TV-MA,1 Season,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,75,ns3,2021-09-24,1,Season
3,tv show,jailbirds new orleans,NaN,NaN,NaN,2021,TV-MA,1 Season,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",49,ns4,2021-09-24,1,Season
4,tv show,kota factory,NaN,"mayur more, jitendra kumar, ranjan raj, alam k...",india,2021,TV-MA,2 Seasons,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,92,ns5,2021-09-24,2,Seasons
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2007,R,158 min,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",20,ns8803,2019-11-20,158,min
8803,tv show,zombie dumb,NaN,NaN,NaN,2018,TV-Y7,2 Seasons,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",8,ns8804,2019-07-01,2,Seasons
8804,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2009,R,88 min,"comedies, horror movies",looking to survive in a world taken over by zo...,55,ns8805,2019-11-01,88,min
8805,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2006,PG,88 min,"children & family movies, comedies","dragged from civilian life, a former superhero...",7,ns8806,2020-01-11,88,min
8806,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2015,TV-14,111 min,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,44,ns8807,2019-03-02,111,min

Los campos de texto deberán estar en minúsculas, sin excepciones

In [420]:
##se usara el metodo lower para cambiar todos los textos a minusculas
data_nexflix['type'] = data_nexflix['type'].str.lower()
data_nexflix['title'] = data_nexflix['title'].str.lower()
data_nexflix['director'] = data_nexflix['director'].str.lower()
data_nexflix['cast'] = data_nexflix['cast'].str.lower()
data_nexflix['country'] = data_nexflix['country'].str.lower()
data_nexflix['listed_in'] = data_nexflix['listed_in'].str.lower()
data_nexflix['description'] = data_nexflix['description'].str.lower()

El campo duration debe convertirse en dos campos: duration_int y duration_type. El primero será un integer y el segundo un string indicando la unidad de medición de duración: min (minutos) o season (temporadas)

In [422]:
##Uso el metodo split para dividir la columna duration 
data_nexflix[['duration_int','duration_type']] = data_nexflix['duration'].str.split(expand=True)

Se guardaran a csv los dataframe ya transformados

In [427]:
data_nexflix.to_csv('data_nexflix_trasformado_utf8.csv',encoding='utf-8')

In [428]:
data_hulu.to_csv('data_hulu_transformado_utf8.csv',encoding='utf-8')

In [429]:
data_amazon.to_csv('data_amazon_transformado_utf8.csv',encoding='utf-8')

In [430]:
datos_disney.to_csv('data_disney_transformado_utf8.csv',encoding='utf-8')

Concatenamos los dataframe a uno solo para trabajar con las consultas

In [432]:
amazon = data_amazon.copy()
disney = datos_disney.copy()
hulu = data_hulu.copy()
nexflix = data_nexflix.copy()

In [459]:
df1 = amazon.append(disney)

C:\Users\USER\AppData\Local\Temp\ipykernel_17004\2502914123.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = amazon.append(disney)

In [460]:
df2 = df1.append(hulu)

C:\Users\USER\AppData\Local\Temp\ipykernel_17004\2935839926.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df1.append(hulu)

In [462]:
df3 = df2.append(nexflix)

C:\Users\USER\AppData\Local\Temp\ipykernel_17004\134474913.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df2.append(nexflix)

In [471]:
df3.columns

Index(['type', 'title', 'director', 'cast', 'country', 'release_year',
       'rating', 'duration', 'listed_in', 'description', 'score', 'Id',
       'date_added', 'duration_int', 'duration_type'],
      dtype='object')

In [472]:
"""En el dataframe hay una columna con una letra en mayusculas 
   y se debe renombrar el campo para terminar para terminar con las transformaciones"""

datas = df3.rename(columns={'Id':'id'})

In [475]:
## vemos que todo este bien 
datas.shape

(22998, 15)

In [477]:
datas.columns ##comprobamos que Id haya cambiado por id

Index(['type', 'title', 'director', 'cast', 'country', 'release_year',
       'rating', 'duration', 'listed_in', 'description', 'score', 'id',
       'date_added', 'duration_int', 'duration_type'],
      dtype='object')

In [478]:
##creamos un csv unico para trabajar con las querys de consulta
datas.to_csv('data_plataformas_movies.csv',encoding='utf-8', index=False)